volumes:
  init-db:
  data-db:

services:
  app:
    build: .
    volumes:
      - .:/djangoProjectFinalVersion
    ports:
      - "8000:8000"
    image: app:djangoProjectFinalVersion
    container_name: blog_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: django
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
      - ./media/images:/media/images
    ports:
      - "27017:27017"
    container_name: mongodb_container

  #db_mongodb_worker_import:
      #image: mongo
      #container_name: "reviews_import"
      #depends_on:
      #  - db
     # volumes:
      #  - ./mongo-seed:/mongo-seed

      #command: mongoimport --host db:27017 --db django --collection rnn_review --type json --file /mongo-seed/reviews_data.json --jsonArray --authenticationDatabase admin --username root --password root
